name: CherokeeTrainingData
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - audioread=2.1.9
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - cryptography=35.0.0
  - cudatoolkit=11.1.1
  - curl=7.71.1
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.0
  - expat=2.4.1
  - ffmpeg=4.3.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - git=2.32.0
  - gitdb=4.0.9
  - gitpython=3.1.24
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.1
  - intel-openmp=2021.3.0
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libogg=1.3.4
  - libopenblas=0.3.17
  - libopus=1.3.1
  - libpng=1.6.37
  - librosa=0.8.1
  - libsndfile=1.0.31
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libuv=1.42.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.3.0
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numba=0.53.1
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1l
  - packaging=21.2
  - pcre=8.45
  - pcre2=10.35
  - perl=5.32.1
  - pillow=7.2.0
  - pip=21.2.4
  - pooch=1.5.2
  - progressbar=2.5
  - pthread-stubs=0.4
  - pycparser=2.20
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.8.2
  - qt=5.9.7
  - readline=8.1
  - requests=2.26.0
  - resampy=0.2.2
  - scikit-learn=0.24.2
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.36.0
  - threadpoolctl=3.0.0
  - tk=8.6.10
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wheel=0.37.0
  - x264=1!161.3030
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - absl-py==1.0.0
    - alembic==1.7.5
    - altair==4.1.0
    - argon2-cffi==21.1.0
    - astor==0.8.1
    - attrs==21.2.0
    - autopage==0.4.0
    - backcall==0.2.0
    - base58==2.1.0
    - bleach==4.1.0
    - blinker==1.4
    - cachetools==4.2.4
    - click==7.1.2
    - cliff==3.10.0
    - cmaes==0.8.2
    - cmd2==2.3.3
    - colorama==0.4.4
    - colorlog==6.4.1
    - debugpy==1.5.1
    - defusedxml==0.7.1
    - denoiser==0.1.4
    - docopt==0.6.2
    - entrypoints==0.3
    - filelock==3.4.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.43.0
    - hydra-colorlog==0.1.4
    - hydra-core==0.11.3
    - importlib-metadata==4.10.0
    - ipykernel==6.4.2
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jinja2==3.0.2
    - jsonschema==4.1.2
    - jupyter-client==7.0.6
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - mako==1.1.6
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mpmath==1.2.1
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.5
    - numpy==1.21.2
    - oauthlib==3.1.1
    - omegaconf==1.4.1
    - optuna==2.10.0
    - pandas==1.3.4
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pbr==5.8.0
    - pescador==2.1.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prettytable==2.5.0
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.21
    - protobuf==3.19.1
    - ptyprocess==0.7.0
    - pyannote-audio==1.1.2
    - pyannote-core==4.3
    - pyannote-database==4.1.1
    - pyannote-metrics==3.1
    - pyannote-pipeline==1.5.2
    - pyarrow==6.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeck==0.7.1
    - pydub==0.25.1
    - pygments==2.10.0
    - pyperclip==1.8.2
    - pyrsistent==0.18.0
    - pystoi==0.3.3
    - pytz==2021.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scipy==1.7.1
    - send2trash==1.8.0
    - shellingham==1.4.0
    - simplejson==3.17.6
    - sortedcollections==2.1.0
    - sortedcontainers==2.4.0
    - sounddevice==0.4.2
    - sqlalchemy==1.4.28
    - stevedore==3.5.0
    - streamlit==1.1.0
    - sympy==1.9
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - terminado==0.12.1
    - testpath==0.5.0
    - toml==0.10.2
    - toolz==0.11.1
    - torch==1.9.1
    - torchaudio==0.9.1
    - torchlibrosa==0.0.7
    - tqdm==4.62.3
    - traitlets==5.1.1
    - typer==0.4.0
    - tzdata==2021.5
    - tzlocal==4.1
    - validators==0.18.2
    - voicefixer==0.0.17
    - watchdog==2.1.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.2
    - widgetsnbextension==3.5.2
    - zipp==3.6.0
